### ISSUE TITLE
About tab - Dropdown: Add "History"; Move "About" to top

### ISSUE THREAD

**Issue by jjmcgra** [IQSS/zeligproject.org#5]
Note that the source file for the About the Project page is currently called "history_name.rst"

New text in Google doc for new History page.  (History of word Zelig).

**Comment by mheppler** [comment]
Based on Gary's feedback, the About page has been updated.

> I would drop the Project and Team pages and combine them into an 'About' page that first lists the Team and then explains the name Zelig.
